services:
  # --- Frontend Service --- 
  frontend:
    build:
      context: ./digital-coach-app # Path to frontend Dockerfile
      target: deps # For development, build up to the 'deps' stage
      # args:
      #   # Pass the environment variables as arguments for build-time use (make sure the names match from .env, Dockerfile, and here)
      #   # Currently, these are null because the env file needs to be consolidated to the root folder first. However, this shouldn't be a problem for now we're using firebase emulators for local development.
      #   - NEXT_PUBLIC_FIREBASE_API_KEY
      #   - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
      #   - NEXT_PUBLIC_FIREBASE_PROJECT_ID
      #   - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
      #   - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
      #   - NEXT_PUBLIC_FIREBASE_APP_ID
      #   - NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
    # Put secrets in the container environment as they're for runtime use
    environment:
      - NODE_ENV=development # Set Node environment to development to do things like enable emulators
    # Required so changes are reflected in Next.js without restarting the container
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./digital-coach-app/.env # load environment variables from .env file (this is specifically for HeyGen API key. TEMPORARY: use environment directive above after env files have been consolidated to the root folder)
    volumes:
      # Mount the frontend code for live development
      - ./digital-coach-app:/app
      - /app/node_modules # Preserve node_modules inside the container
      - /app/.next
    command: yarn dev # Start the Next.js development server
    ports:
      # Expose port 3000 for the frontend
      - "3000:3000"
    depends_on:
      - api # Ensure the backend API is started before the frontend
    networks:
      - app-network # use the shared network to communicate with the backend

  # Firebase Emulator Suite for local development
  firebase:
    # use pre-built image with firebase tools
    image: andreysenov/firebase-tools:latest-node-22-slim
    environment:
      - FUNCTIONS_EMULATOR_TIMEOUT_SECONDS=180
    user: root
    volumes:
      # mount frontend as it contains firebase config and rules
      - ./digital-coach-app:/home/node/app
    working_dir: /home/node/app # set working directory to non-root user's home
    # expose the necessary ports for the emulators
    ports:
      - "9099:9099" # Auth Emulator
      - "8080:8080" # Firestore Emulator
      - "9199:9199" # Storage Emulator
      - "4000:4000" # Firebase UI
      - "5001:5001" # Functions Emulator
    # Start the emulators (that are needed) with the specified config file
    command: firebase emulators:start --inspect-functions --only auth,firestore,storage,functions --project=demo-digital-coach --debug
    networks:
      - app-network # use the shared network to the communicate with the frontend and backend

  # --- Backend Services ---
  # API service 
  api:
    build: ./mlapi # Path to backend Dockerfile
    ports:
      - "8000:8000" # Expose port 8000 for the API
    env_file:
      - ./mlapi/.env # load the environment variables before starting container
    environment:  
      - WORKERS_COUNT=3
      - ENVIRONMENT=development # used when connecting to Firebase to switch between emulators and real services
      - GOOGLE_APPLICATION_CREDENTIALS=/app/digital-coach-firebase-adminsdk.json # directory for firebase admin key
    volumes:
      - ./mlapi:/app # Mount backend code for live development
      - /app/.venv # Preserves the virtual environment inside the container
      - ./mlapi/digital-coach-firebase-adminsdk.json:/app/digital-coach-firebase-adminsdk.json
    command: uvicorn main:app --host 0.0.0.0 --port 8000 # Start the API for development, use --reload for auto-reload but its CPU intensive. This overrides the default CMD in the Dockerfile which is meant for production.
    depends_on:
      - redis # Ensure Redis is started before the API
      - firebase # Ensure firebase starts before the backend tries to connect to it
    networks:
      - app-network # Use the shared network to communicate with the other services

  # Redis for job queue and caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - app-network

  # High priority worker for facial and audio analysis
  high-worker:
    build: ./mlapi
    command: python -m redisStore.worker high
    depends_on:
      - redis
    env_file:
      - ./mlapi/.env # load the environment variables before starting container
    environment:  
      - WORKERS_COUNT=3
      - ENVIRONMENT=development # used when connecting to Firebase to switch between emulators and real services
      - GOOGLE_APPLICATION_CREDENTIALS=/app/digital-coach-firebase-adminsdk.json # directory for firebase admin key
    volumes:
      - ./mlapi/data:/app/data
      - ./mlapi:/app
      - /app/.venv # Preserves the virtual environment inside the container
    networks:
      - app-network
    deploy:
      replicas: 2

  # Default worker for other tasks
  default-worker:
    build: ./mlapi
    command: python -m redisStore.worker default
    depends_on:
      - redis
    env_file:
      - ./mlapi/.env # load the environment variables before starting container
    environment:  
      - WORKERS_COUNT=3
      - ENVIRONMENT=development # used when connecting to Firebase to switch between emulators and real services
      - GOOGLE_APPLICATION_CREDENTIALS=/app/digital-coach-firebase-adminsdk.json # directory for firebase admin key
    volumes:
      - ./mlapi/data:/app/data
      - ./mlapi:/app
      - /app/.venv # Preserves the virtual environment inside the container
    networks:
      - app-network
    deploy:
      replicas: 3

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:

models:
  llm:
    model: ai/qwen3:4B-UD-Q4_K_XL # LLM model we're using
    context_size: 8192 # context size (how much many tokens the model can process at any given time which includes your prompt and the LLM's response), each model has their own max size you can check using `docker model inspect <model name>` (make this smaller if you experience out of memory errors but there needs to be enough context for the LLM to make detailed responses)
    runtime_flags:
      - "--log-prefix" # Enable prefix in log messages
      - "--log-timestamps" # Enable timestamps in log messages
      - "--log-colors" # Enable colored logging
      - "--threads" # Number of CPU threads to use during generation (Docker can use both CPU and GPU but GPU-only is faster)
      - "4"
      - "--batch-size" # batch size for processing prompts (higher = faster processing of prompts, and you may comment this out if you're experiencing performance issues)
      - "1024"
      - "--n-gpu-layers" # number of layers to offload to GPU (total number of layers depends on the model) Docker model runner can use both CPU and GPU of ngl < total number of layers. Lower --ngl if running out of VRAM. Increase --ngl if there's low GPU usage during inference."
      - "20"